### ISSUE TITLE
Murky要做的東西集中區

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/AICH#1]
# 建立專案
- [x] CAFECA-IO/AICH#10

# API 文件
完成以下三隻API文件
- [ ] CAFECA-IO/iSunFA#586
- [ ] CAFECA-IO/iSunFA#587
- [ ] CAFECA-IO/iSunFA#588

# Google API
- [x] CAFECA-IO/AICH#2
- [x] CAFECA-IO/AICH#3
- [ ] CAFECA-IO/AICH#4
- [ ] CAFECA-IO/AICH#5

# llama
- [x] CAFECA-IO/AICH#6
- [x] CAFECA-IO/AICH#7
- [ ] CAFECA-IO/AICH#8
- [ ] CAFECA-IO/AICH#9
- [ ] CAFECA-IO/AICH#24
    - [x] #35 
    - [x] #36 
    - [x] #37 
    - [x] #39 
- [x] CAFECA-IO/AICH#25

# OCR
- [x] CAFECA-IO/AICH#13

# Voucher
- [x] CAFECA-IO/AICH#14
- [x] #48

# Audit Report
- [ ] CAFECA-IO/AICH#15
    - [x] CAFECA-IO/AICH#20 
    - [x] CAFECA-IO/AICH#21 
    - [x] CAFECA-IO/AICH#22  
# Message MQ
- [ ] CAFECA-IO/AICH#19
- [x] CAFECA-IO/AICH#17
- [x] CAFECA-IO/AICH#18

# Bug
- [x] CAFECA-IO/AICH#29
- [x] #42
- [x] #43
- [x] #46
- [x] #47

# Interface and errorCode
- [x] CAFECA-IO/AICH#28
- [x] #33
- [x] #41
- [x] #44

# 其他
- [x] #51
- [x] #52

**Comment by TinyMurky** [comment]
wont fix
